config/routes.rb
Rails.application.routes.draw do
  root to: 'application#angular'
  mount_devise_token_auth_for 'User', at: 'auth'
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      shallow do
        resources :todo_lists, except: [:new, :edit] do
          resources :todo_tasks, except: [:new, :edit] do 
            resources :todo_comments, only: [:index, :create, :destroy] do
              resources :todo_attachments, only: [:create, :destroy]
            end
          end
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      can :manage, TodoList, user: user
      can :manage, TodoTask, todo_list: { user_id: user.id }
      can :manage, TodoComment, todo_task: { todo_list: { user_id: user.id } }
      can :manage, TodoAttachment, todo_comment: { todo_task: { todo_list: { user_id: user.id } } }
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/todo_attachment.rb
class TodoAttachment < ActiveRecord::Base
	mount_uploader :file, TodoFileUploader

	belongs_to :todo_comment

	validates :file, :todo_comment, presence: true
end

app/models/todo_comment.rb
class TodoComment < ActiveRecord::Base
	belongs_to :todo_task
	has_many :todo_attachments, dependent: :destroy

	validates :todo_task, :body, presence: true
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	validates :user, :title, presence: true

  	belongs_to :user

	has_many :todo_tasks, dependent: :destroy
	default_scope { order(:priority) } 
end

app/models/todo_task.rb
class TodoTask < ActiveRecord::Base
  validates :todo_list, :content, presence: true

  belongs_to :todo_list
  has_many :todo_comments, dependent: :destroy

  default_scope { order(completed_at: :asc, priority: :asc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :omniauthable
  include DeviseTokenAuth::Concerns::User
 
  validates :email, uniqueness: {case_sensitive: false}
  has_many :todo_lists, dependent: :destroy
end

app/controllers/api/v1/todo_attachments_controller.rb
module Api
  module V1
	class TodoAttachmentsController < ApplicationController
	  load_and_authorize_resource :todo_comment
	  load_and_authorize_resource :todo_attachment, through: :todo_comment, shallow: true

	  def create
	    respond_with :api, :v1, @todo_comment.todo_attachments.create(todo_attachment_params)
	  end

	  private

	  def todo_attachment_params
	    params.permit(:file)
	  end
	end
  end
end

app/controllers/api/v1/todo_comments_controller.rb
module Api
  module V1
    class TodoCommentsController < ApplicationController
	    load_and_authorize_resource :todo_task
      load_and_authorize_resource :todo_comment, through: :todo_task, shallow: true

      def index
        respond_with @todo_comments
      end

      def create
        respond_with :api, :v1, @todo_task.todo_comments.create(todo_comment_params)
      end

      def destroy
        respond_with @todo_comment.destroy
      end

      private

      def todo_comment_params
        params.permit(:body)
	  end

    end
  end
end

app/controllers/api/v1/todo_lists_controller.rb
module Api
  module V1
    class TodoListsController < ApplicationController
      load_and_authorize_resource

      def index
        respond_with @todo_lists
      end

      def show
        respond_with @todo_list
      end

      def create
        respond_with :api, :v1, current_user.todo_lists.create(todo_list_params)
      end

      def update
        respond_with @todo_list.update(todo_list_params)
      end

      def destroy
        respond_with @todo_list.destroy
      end

      private

      def todo_list_params
        params.permit(:title, :priority, :todo_tasks)
      end
    end
  end
end

app/controllers/api/v1/todo_tasks_controller.rb
module Api
  module V1
    class TodoTasksController < ApplicationController
	    load_and_authorize_resource :todo_list
      load_and_authorize_resource :todo_task, through: :todo_list, shallow: true

      def index
        respond_with @todo_tasks
      end

      def create
        respond_with :api, :v1, @todo_list.todo_tasks.create(todo_task_params)
      end

      def update
        respond_with do |format|
          format.json { render(json: @todo_task.update(todo_task_params), status: 200) }
        end
      end

      def destroy
        respond_with @todo_task.destroy
      end

      private

      def todo_task_params
        params.permit(:content, :completed_at, :priority, :due_date)
	    end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format.json? }
  respond_to :json

  def angular
  	render	'layouts/application'
  end

  def default_serrializer_options
  	{root: false}
  end


  rescue_from CanCan::AccessDenied do |exception|
    render json: {error: exception.message}, status: :forbidden
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_attachments_helper.rb
module TodoAttachmentsHelper
end

app/helpers/todo_comments_helper.rb
module TodoCommentsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todo_tasks_helper.rb
module TodoTasksHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h2>Complete the test task for Ruby Garage</h2>
<table class="table table-striped">
  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to edit_todo_list_path(todo_list) do %>
          <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
        </td>
        <td><%= link_to todo_list, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="glyphicon glyphicon-trash"></i>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_todo_list_path, :class => 'btn btn-lg btn-primary' do %>
<span class="glyphicon glyphicon-plus"></span><%= 'Add TODO list' %>
<% end %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
  <div class="panel-heading">
  <h3 class="panel-title">Title:</h3>
  </div>
  <div class="panel-body"><%= @todo_list.title %></div>
</div>

<div id="todo_items_wrapper">
	<%= render @todo_list.todo_tasks %>
	<div id="form">
		<%= render "todo_tasks/form" %>
	</div>
</div>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_tasks/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_tasks.build]) do |f| %>
	<%= f.text_field :content, placeholder: "New Todo" %>
	<%= f.submit %>
<% end %>

app/views/todo_tasks/_todo_task.html.erb
<div class="panel panel-info">
  <% if todo_task.completed? %>
     <div class="complete">
      <%= link_to "Mark as Complete", complete_todo_list_todo_task_path(@todo_list, todo_task.id), method: :patch %>
    </div>
	</div>
	<div class="todo_task">
		<p style="opacity: 0.4"><strike><%= todo_task.content %></strike></p>
	</div>
	<div class="trash">
		<%= link_to "Delete", todo_list_todo_task_path(@todo_list, todo_task.id), method: :delete, data: { confirm: "Are you sure?" } %>
	</div>

  <% else %>
    
    <div class="complete">
      <%= link_to "Mark as Complete", complete_todo_list_todo_task_path(@todo_list, todo_task.id), method: :patch %>
    </div>
    <div class="todo_task">
      <p><%= todo_task.content %></p>
    </div>
    <div class="trash">
    	<%= link_to "Delete", todo_list_todo_task_path(@todo_list, todo_task.id), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>